include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated"

formatter:
  trailing_commas: preserve
  page_width: 80

linter:
  rules:
    - prefer_relative_imports
    - unawaited_futures
